apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit
  namespace: default
spec:
  limits:
    - type: Container
      default:
        memory: "128Mi"
        cpu: "200m"
      defaultRequest:
        memory: "64Mi"
        cpu: "100m"
      max:
        memory: "512Mi"
        cpu: "1000m"
      min:
        memory: "32Mi"
        cpu: "50m"

    - type: Pod
      max:
        memory: "1Gi"
        cpu: "2000m"

    - type: PersistentVolumeClaim
      max:
        storage: "10Gi"
      min:
        storage: "1Gi"
