# --- BestEffort --- 
apiVersion: v1
kind: Pod
metadata:
  name: besteffort-pod
spec:
  containers:
    - name: app
      image: nginx:alpine
---
# --- Burstable ---
apiVersion: v1
kind: Pod
metadata:
  name: burstable-pod
spec:
  containers:
    - name: app
      image: nginx:alpine
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "500m"
---
# --- Guaranteed ---
apiVersion: v1
kind: Pod
metadata:
  name: guaranteed-pod
spec:
  containers:
    - name: app
      image: nginx:alpine
      resources:
        requests:
          memory: "128Mi"
          cpu: "200m"
        limits:
          memory: "128Mi"
          cpu: "200m"

