apiVersion: v1
kind: Pod
metadata:
  name: app-env-demo
spec:
  containers:
    - name: app
      image: nginx:alpine

      env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV

        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL

      envFrom:
        - configMapRef:
            name: app-config
