apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: default
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      nodeSelector:
        monitoring: enabled

      hostNetwork: true
      hostPID: true

      tolerations:
        - operator: Exists

      containers:
        - name: node-exporter
          image: prom/node-exporter:latest
          ports:
            - containerPort: 9100
              hostPort: 9100
          args:
            - '--path.rootfs=/host'
          volumeMounts:
            - name: root
              mountPath: /host
              readOnly: true

          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"

      volumes:
        - name: root
          hostPath:
            path: /
