apiVersion: v1
kind: Pod
metadata:
  name: app-with-init
  labels:
    app: myapp
spec:
  initContainers:
    - name: wait-for-db
      image: busybox:1.35
      command: ['sh', '-c', 'echo waiting for db...; sleep 5; echo DB is ready!']
      
    - name: setup-config
      image: busybox:1.35
      command: ['sh', '-c', 'echo setting up config...; echo app_env=production > /config/app.env']
      volumeMounts:
        - name: config-vol
          mountPath: /config

  containers:
    - name: main-app
      image: nginx:alpine
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config

  volumes:
    - name: config-vol
      emptyDir: {}
