apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
spec:
  containers:
    - name: app
      image: nginx:alpine
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html

  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: my-pvc
